# Generated by Django 5.2 on 2025-10-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
