# Generated by Django 5.2 on 2025-10-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_profile_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp_password_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
